### ISSUE TITLE
Add support for gitlabCI

### ISSUE THREAD

**Issue by DieracDelta** [bachp/junit-report-rs#20]
GitlabCI requires attachments in the [following format](https://docs.gitlab.com/ee/ci/unit_test_reports.html):
```xml
<testcase time="1.00" name="Test">
  <system-out>[[ATTACHMENT|/path/to/some/file]]</system-out>
</testcase>
```
When I try to generate this with a `TestCaseBuilder` by calling `set_system_out("my_path")`, the resulting system out contents are wrapped in a `CDATA`. This is not parsed correctly by gitlabCI. 

 Perhaps we could add an `add_attachment` function to TestCaseBuilder which would generate `system-out` but without the CDATA?

**Comment by bachp** [comment]
I'm thinking if `set_system_out` should take a enum as argument that could be one of the following: Plain, Cdata, Attachement. This way all cases could be handled.

**Comment by bachp** [comment]
@DieracDelta Any feedback if the enum solution would work for you?

**Comment by bachp** [comment]
@DieracDelta I didn't get any feedback. Closing, feel free to re-open if this is still an issue.
