### ISSUE TITLE
Re-export `quick_xml::Error`

### ISSUE THREAD

**Issue by GeorgeHahn** [bachp/junit-report-rs#27]
Thanks for the useful crate!

It would be helpful if this crate exported or wrapped the `quick_xml::Error` type that is returned from `Report::write_xml()`

I'm happy to contribute this if you're interested.

**Comment by bachp** [comment]
I was thinking about using proper erro types with [anyhow](https://docs.rs/anyhow/latest/anyhow/). But this would be a breaking change.

So I think for now your proposal makes sense, please submit a PR.

**Comment by msfjarvis** [comment]
> I was thinking about using proper erro types with [anyhow](https://docs.rs/anyhow/latest/anyhow/). But this would be a breaking change.

FWIW, for library code you would typically want to use [thiserror](https://lib.rs/crates/thiserror) instead.

> ## Comparison to anyhow
>
> Use thiserror if you care about designing your own dedicated error type(s) so
that the caller receives exactly the information that you choose in the event of
failure. This most often applies to library-like code. Use [Anyhow] if you don't
care what error type your functions return, you just want it to be easy. This is
common in application-like code.

[Anyhow]: https://github.com/dtolnay/anyhow

**Comment by bachp** [comment]
@msfjarvis Thank you, [thiserror](https://lib.rs/crates/thiserror) was actually what I had in mind.
