### ISSUE TITLE
strip-ansi-escapes dependency no longer used.

### ISSUE THREAD

**Issue by mjpieters** [bachp/junit-report-rs#47]
You have a dependency on strip-ansi-escapes, but this crate is no longer used.

Even when it was used, it was only used in the _tests_ for `report.rs`, so it should have been a dev-dependency.

You could either just drop it, _or_ junit-report could explicitly support stripping ANSI code from system output. After all, these are the most common source of invalid XML output (the 0x1B ESC codepoint is explicitly not allowed in XML).

**Comment by bachp** [comment]
Thanks for reporting this. I think for now I will just drop it. If there is a need for striping ansi escape sequences it can be added as a new feature in the future.
