### ISSUE TITLE
system-out and system-err support

### ISSUE THREAD

**Issue by Puciek** [bachp/junit-report-rs#8]
Heya!

I've ran into this crate, and so far loving it - but also it is currently lacking support for providing system-out and system-err to the testcase. Unless you have plans on doing it (I see them marked as todo in code), I'm happy to take a whack, and highly appreciate any pointers you may have to get it up and running :)

**Comment by bachp** [comment]
Hi

Thanks for your interest. I would welcome the contribution.

What I see it would just mean adding the two fields as `Option<>` to the corresponding section.

Let me know if you run into any issues. Looking forward to your PR.

**Comment by bachp** [comment]
Implemented in #10
